# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.CharField(default='generateTrackingCode()', max_length=30, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=500)),
                ('weight', models.CharField(max_length=30)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('has_arrived', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=500)),
                ('customer_tel', models.CharField(max_length=15)),
            ],
        ),
    ]
